### ISSUE TITLE
[Enhancement]: merge both 2204 snaps in a single branch

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snapcrafters/ffmpeg-2404-sdk#4]
### What changes would you like?

It might be better to split this repo into multiple repositories; one for each snap. The inside those repos, we can have a branch `candidate` for the `candidate` channel of that snap. This will make it easier to add our automation.

**Comment by soumyaDghosh** [comment]
This snap and the webkitgtk snap both follows the model of the gnome-sdk which I created with the help of @kenvandine. Each of this branch is connected with launchpad, where I have created an organization named `ffmpeg-sdk` and it has two snaps under each. Launchpad should be able to automatically find out if something has changed in github repo or not, but it never worked properly. It also never automatically created the build of a snap package on the change of commit in the source branch. Now, if we divide this repo, wouldn't we get lost with multiple repos, cause with every new base we'll have to create a new repo. Also, if we needed new tracks for older versions, we'll again need another repo(probably). Wouldn't the development be cluttered between different repos, making the maintainence difficult?

**Comment by merlijn-sebrechts** [comment]
> Now, if we divide this repo, wouldn't we get lost with multiple repos, cause with every new base we'll have to create a new repo.

I don't think this is an issue. Bases only come out every 2 years.

> Also, if we needed new tracks for older versions, we'll again need another repo(probably).

We can definitely have branches for _tracks_!

> Wouldn't the development be cluttered between different repos, making the maintainence difficult?

In my opinion, we should do this:

* If there is a lot of _shared common code_ between different snaps, then they should be _different branches_, so that we can easily merge patches into multiple branches.
* If there is _no shared code_ between different snaps, then they should be _different repositories_, so that we can easily separate the bugtrackers, users can easily find the code, etc.

**Comment by merlijn-sebrechts** [comment]
There is also the possibility of having multiple `snapcraft.yaml` files in a single branch in a single repo. That's what we're going to do with the different Eclipse flavors.

**Comment by soumyaDghosh** [comment]
Well the sdk and content snaps obviously shares the same code. First the sdk is built in launchpad and uploaded to store. Then the sdk snap is downloaded in the content snap and unnecessary files(pc, header files) are removed.

**Comment by merlijn-sebrechts** [comment]
Note: with "code" I meant the code in `snapcraft.yaml`, not the contents of your snap.

The advantage of having it in a single repository, is that you can easily merge patches between branches. But that is only important when the `snapcraft.yaml` files look a lot like each other.

**Comment by soumyaDghosh** [comment]
Ummm... Then if it's really necessary, can we do it this way, one repo for the content snaps and one for the sdks, now with each base a new branch for the new/old one. Uses reporting issues, will report them in the content snap repo, specifying the version of ffmpeg?

**Comment by merlijn-sebrechts** [comment]
We can have a branch for each base if you think that will help maintenance.

Honestly, the more I think about, the more I think we should simply have two `snapcraft.yaml` files in a single branch in a single repository. Since each release of `ffmpeg-2204` is tied to a release of `ffmpeg-2204-sdk`, I think it's good that a single checkout has them both. Then we can use our automation to do the following:

1. Checkout `core22` branch
1. Build `ffmpeg-2204-sdk`, push to `candidate`, save that specific revision number
1. Update the snapcraft.yaml of `ffmpeg-2204` to point to that specific revision number in `candidate`
1. Build `ffmpeg-2204`, push to `candidate`, save that specific revision number
1. Create an issue pointing to both revision numbers asking for testing

That way, we can publish both `ffmpeg-2204-sdk`, and `ffmpeg-2204` with a single command to `stable`. People using the `stable` version of the snap will never have a disparity between the SDK and the regular snap.

What do you think of this?

**Comment by merlijn-sebrechts** [comment]
For future bases, we can create a new branch for each. e.g. `core24`

**Comment by soumyaDghosh** [comment]
Yup, this sounds great. Can you point me the ci which can do so? or, may be we can just have it under two different folders?

like `ffmpeg-2204-sdk/snapcraft.yaml` and `ffmpeg-2204/snapcraft.yaml`

**Comment by merlijn-sebrechts** [comment]
We need some changes to our CI scripts so that we can pass a snapcraft.yaml file to them. I filed an issue for that: https://github.com/snapcrafters/ci/issues/4

Once that issue is resolved, we can create a workflow like below:

```yaml
name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "2204" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-architectures:
    name: 🖥 Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: 🖥 Get snap architectures
        id: get-architectures
        uses: snapcrafters/ci/get-architectures@main
        with:
          snapcraft-yaml-path: ffmpeg-2204-sdk/snapcraft.yaml


  release-sdk:
    name: 🚢 Release SDK to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: 🚢 Release to latest/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
          snapcraft-yaml-path: ffmpeg-2204-sdk/snapcraft.yaml


  release:
    name: 🚢 Release to latest/candidate
    needs: [release-sdk, get-architectures]
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: 🚢 Release to latest/candidate
        uses: snapcrafters/ci/release-to-candidate@main
        with:
          architecture: ${{ matrix.architecture }}
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
          snapcraft-yaml-path: ffmpeg-2204/snapcraft.yaml

  call-for-testing-sdk:
    name: 📣 Create SDK call for testing
    needs: [release, release-sdk, get-architectures]
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snapcraft-yaml-path: ffmpeg-2204-sdk/snapcraft.yaml

  call-for-testing:
    name: 📣 Create call for testing
    needs: [release, release-sdk, get-architectures]
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: 📣 Create call for testing
        id: issue
        uses: snapcrafters/ci/call-for-testing@main
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snapcraft-yaml-path: ffmpeg-2204/snapcraft.yaml
```
